# Generated by Django 5.0.6 on 2024-07-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
