# Generated by Django 5.0.6 on 2024-07-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('potential', '0002_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shot_accuracy', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('pass_accuracy', models.IntegerField(default=0)),
                ('dribbles', models.IntegerField(default=0)),
                ('dribbles_success_rate', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('tackle_success_rate', models.IntegerField(default=0)),
                ('offsides', models.IntegerField(default=0)),
                ('fouls_committed', models.IntegerField(default=0)),
                ('possession_won', models.IntegerField(default=0)),
                ('possession_lost', models.IntegerField(default=0)),
            ],
        ),
    ]
