# Generated by Django 5.0.6 on 2024-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dribbles_success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='pass_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='shot_accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='tackle_success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
