# Generated by Django 5.0.6 on 2025-01-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0004_alter_player_dribbles_success_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('training', 'Training'), ('official_game', 'Official Game'), ('random', 'Random')], default='random', max_length=20),
        ),
    ]
