# Generated by Django 5.0.6 on 2025-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0005_player_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='official_game_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='random_stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='training_stats',
            field=models.JSONField(default=dict),
        ),
    ]
