# Generated by Django 5.0.6 on 2025-02-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potential', '0006_player_official_game_stats_player_random_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='official_game_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='random_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='training_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
